package com.msc.facturierws.entity;

//

import com.msc.rest.tokenrestjersey.TokenEntity;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HistoriqueFacture.java
//  @ Date : 13/11/2016
//  @ Author : 
//
//




public class HistoriqueFacture extends TokenEntity{
	private Client client;
	private Template template;
	private Facture facture;

    /**
     * @return the client
     */
    public Client getClient() {
        return client;
    }

    /**
     * @param client the client to set
     */
    public void setClient(Client client) {
        this.client = client;
    }

    /**
     * @return the template
     */
    public Template getTemplate() {
        return template;
    }

    /**
     * @param template the template to set
     */
    public void setTemplate(Template template) {
        this.template = template;
    }

    /**
     * @return the facture
     */
    public Facture getFacture() {
        return facture;
    }

    /**
     * @param facture the facture to set
     */
    public void setFacture(Facture facture) {
        this.facture = facture;
    }
        
        
}
