package com.msc.facturierws.entity;

//
import com.msc.dao.daoproject.annotation.Id;
import com.msc.dao.daoproject.annotation.Name;
import com.msc.dao.daoproject.annotation.StaticField;
import com.msc.rest.tokenrestjersey.TokenEntity;
import java.util.Arrays;
import java.util.List;
import javax.ws.rs.FormParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.xml.bind.annotation.XmlRootElement;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MonEntreprise.java
//  @ Date : 13/11/2016
//  @ Author : 
//
//
@Name(name = "monEntreprise")
@XmlRootElement(name = "MonEntreprise")
@Produces(MediaType.APPLICATION_JSON)
public class MonEntreprise extends TokenEntity {

    @StaticField
    public static final String SEPARATOR_MENTION_LEGAL = ";";
    
    @Id
    private Integer id;

    @FormParam("nom")
    private String nom;
    @FormParam("prenom")
    private String prenom;
    @FormParam("raisonSociale")
    private String raisonSociale;
    @FormParam("adresse")
    private String adresse;
    @FormParam("codePostal")
    private String codePostal;
    @FormParam("ville")
    private String ville;
    @FormParam("email")
    private String email;
    @FormParam("telephone")
    private String telephone;

    @FormParam("titulairecompte")
    private String titulairecompte;
    @FormParam("iban")
    private String iban;
    @FormParam("bic")
    private String bic;
    @FormParam("siren")
    private String siren;
    @FormParam("mentionLegales")
    private String mentionLegales;

    /**
     * @return the titulairecompte
     */
    public String getTitulairecompte() {
        return titulairecompte;
    }

    /**
     * @param titulairecompte the titulairecompte to set
     */
    public void setTitulairecompte(String titulairecompte) {
        this.titulairecompte = titulairecompte;
    }

    /**
     * @return the iban
     */
    public String getIban() {
        return iban;
    }

    /**
     * @param iban the iban to set
     */
    public void setIban(String iban) {
        this.iban = iban;
    }

    /**
     * @return the bic
     */
    public String getBic() {
        return bic;
    }

    /**
     * @param bic the bic to set
     */
    public void setBic(String bic) {
        this.bic = bic;
    }

    /**
     * @return the siren
     */
    public String getSiren() {
        return siren;
    }

    /**
     * @param siren the siren to set
     */
    public void setSiren(String siren) {
        this.siren = siren;
    }

    /**
     * @return the mentionLegale
     */
    public List<String> getMentionLegalesList() {
        return Arrays.asList(mentionLegales.split("\\"+SEPARATOR_MENTION_LEGAL));
    }

    public void setMentionLegalesList(List<String> mls) {
        StringBuilder sb = new StringBuilder();
        for (String ml : mls){
            sb.append(ml);
            sb.append(SEPARATOR_MENTION_LEGAL);
        }
        sb = sb.delete(sb.length()-1, sb.length());
        this.mentionLegales = sb.toString();
    }

    
    /**
     * @return the mentionLegalesStr
     */
    public String getMentionLegales() {
        return mentionLegales;
    }

    /**
     * @param mentionLegalesStr the mentionLegalesStr to set
     */
    public void setMentionLegales(String mentionLegalesStr) {
        this.mentionLegales = mentionLegalesStr;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the nom
     */
    public String getNom() {
        return nom;
    }

    /**
     * @param nom the nom to set
     */
    public void setNom(String nom) {
        this.nom = nom;
    }

    /**
     * @return the prenom
     */
    public String getPrenom() {
        return prenom;
    }

    /**
     * @param prenom the prenom to set
     */
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    /**
     * @return the raisonSociale
     */
    public String getRaisonSociale() {
        return raisonSociale;
    }

    /**
     * @param raisonSociale the raisonSociale to set
     */
    public void setRaisonSociale(String raisonSociale) {
        this.raisonSociale = raisonSociale;
    }

    /**
     * @return the adresse
     */
    public String getAdresse() {
        return adresse;
    }

    /**
     * @param adresse the adresse to set
     */
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    /**
     * @return the codePostal
     */
    public String getCodePostal() {
        return codePostal;
    }

    /**
     * @param codePostal the codePostal to set
     */
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }

    /**
     * @return the ville
     */
    public String getVille() {
        return ville;
    }

    /**
     * @param ville the ville to set
     */
    public void setVille(String ville) {
        this.ville = ville;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the telephone
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * @param telephone the telephone to set
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

}
