package com.msc.facturierws.entity;

//
import com.msc.rest.tokenrestjersey.TokenEntity;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Template.java
//  @ Date : 13/11/2016
//  @ Author : 
//
//
public class Template extends TokenEntity {

    private Integer id;
    private String templateUrl;

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the templateUrl
     */
    public String getTemplateUrl() {
        return templateUrl;
    }

    /**
     * @param templateUrl the templateUrl to set
     */
    public void setTemplateUrl(String templateUrl) {
        this.templateUrl = templateUrl;
    }
}
